version: 2
jobs:
  build:
    docker:
      - image: nwnxee/builder
    steps:
      - checkout
      - run: CC="gcc -m32" CXX="g++ -m32" cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .
      - run: make all
      - run: Scripts/packageNWScript.sh
      - run: zip Binaries/NWNX-EE.zip Binaries/NWNX_*.so
      - run: rm Binaries/NWNX_*.so
      - store_artifacts:
          path: Binaries


workflows:
  version: 2
  build_nwnxee:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/